kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mongodb
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
